name: Frontend Lint

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'member-portal-frontend/**'

permissions:
  statuses: write
  contents: read
  pull-requests: write

defaults:
  run:
    working-directory: member-portal-frontend

jobs:
  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: pending
          context: Check pull request (Frontend)

      - uses: actions/checkout@v4

      - run: corepack enable
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"
          cache-dependency-path: member-portal-frontend/pnpm-lock.yaml

      - name: Install dependencies
        run: pnpm install --frozen-lockfile
        working-directory: ./member-portal-frontend

      - uses: reviewdog/action-eslint@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          reporter: github-pr-review
          workdir: member-portal-frontend
          fail_on_error: 'true'

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: Check pull request (Frontend)
